### ISSUE TITLE
Add the layout for the user's profile

### ISSUE THREAD

**Issue by andreamancuso098** [LucaFalasca/Hunts#161]
Creare il layout del profile di un utente

**Comment by LucaFalasca** [comment]
![IMG_20210705_113305__01.jpg](https://user-images.githubusercontent.com/30274870/124451129-5f0cdf00-dd85-11eb-98d7-43e4e944e5bb.jpg)

**Comment by andreamancuso098** [comment]
@LucaFalasca quel rating hunts può diventare attributo di user sul database direttamente?

**Comment by LucaFalasca** [comment]
No, meglio di no perché è un valore calcolato. Però può essere un attributo dell'entità hunt sulla parte java
