### ISSUE TITLE
Implements save and publish on ManageHunt

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Hunts#167]
Devi implementare il save and publish che semplicemente mettere la mappa pubblica e salvare

**Comment by andreamancuso098** [comment]
Tre bottoni:
- Save: salva l'hunt senza uscire dalla schermata. L'hunt rimane private;
- Save & exit: salva l'hunt uscendo dalla schermata e tornando al main menu. L'hunt rimane private;
- Save & public: salva l'hunt uscendo dalla schermata. L'hunt diventa public
