### ISSUE TITLE
When i click the button for cancelling the search it doesn't work

### ISSUE THREAD

**Issue by andreamancuso098** [LucaFalasca/Hunts#185]
@LucaFalasca il pezzo incriminato è questo praticamente se non metto il nome e riclicco sulla ricerca funziona tutto, se invece clicco l'altro pulsato per cancellare la ricerca non funziona, nonostante il primo richiami il secondo se la text field è vuota
    ```
@FXML
    void handleSearch(ActionEvent event) {
    	var searchName = tfSearchName.getText();
    	
    	if(searchName.equals("")) {
    		handleDeleteSearch(event);
    	}
    	else {
    		var controllerPlay = new PlayHuntControl();
			huntBeans = controllerPlay.getHuntsBySearch(searchName);
    	}
	    		
    	huntsList.setAll(huntBeans);
    }
    
    @FXML
    void handleDeleteSearch(ActionEvent event) {
		huntBeans = controller.getAllHunts();
    }
```

**Comment by LucaFalasca** [comment]
Mm, molto strano devo dire

**Comment by andreamancuso098** [comment]
Lo penso anche io, è per questo che ti ho messo anche il codice. Però l'ho provato ed uno funziona e l'altro no

**Comment by LucaFalasca** [comment]
Ho risolto il problema, semplicemente il risultato della query lo mettevi nella lista di bean non osservabile senza poi aggiungerla a quella osservabile (o meglio dire in uno dei metodi lo facevi e nell'altro no). Non capisco perchè ti ostini ad usare due liste (una osservabile e una non) quanda basta usare quella osservabile e basta
