### ISSUE TITLE
Populate List views in Main menu

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Hunts#39]
Bisogna implementare il riempimento delle list View nel menu principale per permettere la modifica di Hunt e Mappe, e anche per giocare alle Hunt.

 Seguendo questo schema
![immagine](https://user-images.githubusercontent.com/30274870/119127933-45157800-ba35-11eb-9131-14a1d0ac0951.png)

**Comment by andreamancuso098** [comment]
Aggiunte le listCell per ogni item.
In totale ci sono 3 item.

**Comment by andreamancuso098** [comment]
https://stackoverflow.com/questions/19588029/customize-listview-in-javafx-with-fxml
